### ISSUE TITLE
developer.nabto.com link does not work

### ISSUE THREAD

**Issue by shastrinvs** [nabto/unabto-cc3200#1]
Hi

I am trying to recreate a bidirectional audio streaming using CC3200 and nabto. I am unable to find the developer.nabto.com link mentioned in Step 4 .

Regards

Vijay

**Comment by nabto** [comment]
Hi there,

That is an outdated link, please use https://console.cloud.nabto.com instead - you can retrieve the same information (device id and key). I will update the wrong link, thanks for the info!

Ulrik
